coverage:
  fixes:
  - "/usr/local/bin/::keylime/cmd/"
  - "/usr/local/lib/python*/site-packages/keylime-*/::"
comment:
  layout: "flags,files"
  behavior: default
  require_changes: false
  require_base: no
